site_name: MkDocs Template
site_url: https://learn-with-me.github.io/mkdocs-template/
repo_url: https://github.com/learn-with-me/mkdocs-template
docs_dir: 'src'

theme:
  name: material
  logo: assets/images/logo.png
#   favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
  palette: 
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.indexes
    - navigation.top
    # - toc.integrate
  plugins:
    - tags
plugins:
  - search
  - git-revision-date-localized
extra:
  homepage: https://learn-with-me.github.io/mkdocs-template/
  copyright: Copyright &copy; 2022 - 2023 goel4ever
  analytics:
    provider: google
    property: G-RJP1KY6XG1
